### ISSUE TITLE
long/wide in docs / function names

### ISSUE THREAD

**Issue by mabafaba** [agualtieri/dataqualitycontrol#2]
`quality_checks_log_to_long_format` is I think a bit unclear, especially for people not familiar with the "long" / "wide" connotation. Don't have a better idea at hand either though ..

**Comment by agualtieri** [comment]
Right, I will think about a new name. I need to work on this function anyways. I am still trying to figure out how to have one line par variable but I have an idea...

**Comment by agualtieri** [comment]
Done. I added a new function called "separate_on_multiple" that does the job.
